/**
 * File: dbGlobalLists.js
 * ----------------------------------------------------------------------------
 * Purpose:
 *   - Contains global arrays/objects that define the database columns 
 *     and their user-friendly labels.
 *   - Eliminates duplication across multiple scripts (itemList.js, 
 *     importWizard.js, etc.).
 * Usage:
 *   - Load this file FIRST (e.g. <script src="./src/renderer/js/dbGlobalLists.js">),
 *     so all other scripts can reference these globals on `window`.
 */

/** 
 * (A) ITEM LIST
 *     - The columns from item_list (now 95 total, with the 4 extra UPC columns).
 */

// 1) The DB column order for item_list:
window.DB_COLUMNS_ITEM = [
  "item_id",
  "parent_item_id",
  "is_parent",
  "parent_sku",
  "alternate_lookup",
  "item_name",
  "item_description",
  "item_type",
  "attribute",
  "standard_color",
  "size",
  "gender",
  "online_store",
  "for_sale",
  "item_notes",
  "custom_price_1",
  "regular_price",
  "msrp",
  "quantity_on_hand",
  "average_unit_cost",
  "qty_1",
  "qty_2",
  "qty_3",
  "qty_4",
  "qty_5",
  "qty_6",
  "qty_7",
  "reorder_point_1",
  "reorder_point_2",
  "reorder_point_3",
  "reorder_point_4",
  "reorder_point_5",
  "reorder_point_6",
  "reorder_point_7",
  "last_received_date",
  "sold_in_ecommerce",
  "department_code",
  "department_name",
  "vendor_code",
  "vendor_name",
  "upc",
  "base_unit_of_measure",
  "width",
  "height",
  "length",
  "weight",
  "custom_field_1",
  "custom_field_2",
  "custom_field_3",
  "custom_field_4",
  "custom_field_5",
  "manufacturer",
  "serial_tracking",
  "asset_account",
  "cogs_account",
  "income_account",
  "eligible_for_commission",
  "eligible_for_rewards",
  "previous_system_id",
  "qb_listid",
  "po_number",
  "print_tags",
  "sync_to_mobile",
  "tax_code",
  "previous_creation_date",
  "created_date",
  "updated_at",
  "external_sync_id",
  "sync_shopify",
  "sync_amazon",
  "sync_walmart",
  "sync_ebay",
  "sync_etsy",
  "sync_marketplace1",
  "sync_marketplace2",
  "compare_at_price",
  "previous_last_received_date",
  "brief_description",
  "custom_price_2",
  "custom_price_3",
  "custom_price_4",
  "unit_cost",
  "image_url_1",
  "image_url_2",
  "image_url_3",
  "image_url_4",
  "image_url_5",
  "image_url_6",
  "video_url",
  "item_class",
  "available_qty",
  // The newly added UPC fields:
  "UPC_1",
  "UPC_2",
  "UPC_3",
  "UPC_4"
];

// 2) Labels for those columns:
window.DB_COLUMN_LABELS_ITEM = {
  item_id: "Item ID",
  parent_item_id: "Parent Item ID",
  is_parent: "Is Parent",
  parent_sku: "Parent SKU",
  alternate_lookup: "Alternate Lookup",
  item_name: "Item Name",
  item_description: "Item Description",
  item_type: "Item Type",
  attribute: "Attribute",
  standard_color: "Standard Color",
  size: "Size",
  gender: "Gender",
  online_store: "Online Store",
  for_sale: "For Sale",
  item_notes: "Item Notes",
  custom_price_1: "Custom Price 1",
  regular_price: "Regular Price",
  msrp: "MSRP",
  quantity_on_hand: "Quantity on Hand",
  average_unit_cost: "Average Unit Cost",
  qty_1: "Qty 1",
  qty_2: "Qty 2",
  qty_3: "Qty 3",
  qty_4: "Qty 4",
  qty_5: "Qty 5",
  qty_6: "Qty 6",
  qty_7: "Qty 7",
  reorder_point_1: "Reorder Point 1",
  reorder_point_2: "Reorder Point 2",
  reorder_point_3: "Reorder Point 3",
  reorder_point_4: "Reorder Point 4",
  reorder_point_5: "Reorder Point 5",
  reorder_point_6: "Reorder Point 6",
  reorder_point_7: "Reorder Point 7",
  last_received_date: "Last Received Date",
  sold_in_ecommerce: "Sold in Ecommerce",
  department_code: "Department Code",
  department_name: "Department Name",
  vendor_code: "Vendor Code",
  vendor_name: "Vendor Name",
  upc: "UPC",
  base_unit_of_measure: "Base Unit of Measure",
  width: "Width",
  height: "Height",
  length: "Length",
  weight: "Weight",
  custom_field_1: "Custom Field 1",
  custom_field_2: "Custom Field 2",
  custom_field_3: "Custom Field 3",
  custom_field_4: "Custom Field 4",
  custom_field_5: "Custom Field 5",
  manufacturer: "Manufacturer",
  serial_tracking: "Serial Tracking",
  asset_account: "Asset Account",
  cogs_account: "COGS Account",
  income_account: "Income Account",
  eligible_for_commission: "Eligible for Commission",
  eligible_for_rewards: "Eligible for Rewards",
  previous_system_id: "Previous System ID",
  qb_listid: "QB List ID",
  po_number: "PO Number",
  print_tags: "Print Tags",
  sync_to_mobile: "Sync to Mobile",
  tax_code: "Tax Code",
  previous_creation_date: "Previous Creation Date",
  created_date: "Created Date",
  updated_at: "Updated At",
  external_sync_id: "External Sync ID",
  sync_shopify: "Sync Shopify",
  sync_amazon: "Sync Amazon",
  sync_walmart: "Sync Walmart",
  sync_ebay: "Sync eBay",
  sync_etsy: "Sync Etsy",
  sync_marketplace1: "Sync Marketplace 1",
  sync_marketplace2: "Sync Marketplace 2",
  compare_at_price: "Compare at Price",
  previous_last_received_date: "Previous Last Received Date",
  brief_description: "Brief Description",
  custom_price_2: "Custom Price 2",
  custom_price_3: "Custom Price 3",
  custom_price_4: "Custom Price 4",
  unit_cost: "Unit Cost",
  image_url_1: "Image URL 1",
  image_url_2: "Image URL 2",
  image_url_3: "Image URL 3",
  image_url_4: "Image URL 4",
  image_url_5: "Image URL 5",
  image_url_6: "Image URL 6",
  video_url: "Video URL",
  item_class: "Item Class",
  available_qty: "Available Qty",

  // NEW UPC columns
  UPC_1: "UPC 1",
  UPC_2: "UPC 2",
  UPC_3: "UPC 3",
  UPC_4: "UPC 4"
};

/**
 * (B) FUTURE LISTS
 * If you have vendor_list, customer_list, etc., define them here:
 *   window.DB_COLUMNS_VENDOR = [...];
 *   window.DB_COLUMN_LABELS_VENDOR = {...};
 *
 *   window.DB_COLUMNS_CUSTOMER = [...];
 *   window.DB_COLUMN_LABELS_CUSTOMER = {...};
 * 
 * So you have one unified file for all your global lists/mappings.
 */
